# Setup
title:        CJC
tagline:      æ‚
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       CJC
  url:        http://www.cjc.red

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
